POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV1c2kiLCJpZCI6IjY3NGVkZGMxNDQ2OWZjODk3NzRiNmFlNCIsImlhdCI6MTczMzIyMTk2M30.qzubSRQs1PXkwqRKUwADu3-pLBYb7V2TfXNEVzCfui8

{
    "title": "Uutiset Uusimmat",
    "author": "Uusi Uutinen",
    "url": "https://www.uutiset.fi",
    "likes": 10
}
