DELETE http://localhost:3003/api/blogs/67619b480e401d5c5e8c3674
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBvaXN0YWphIiwiaWQiOiI2NzYwN2QyZTM4NjRkZmY4ZTkzY2Q4YTgiLCJpYXQiOjE3MzQ0NTAxMzZ9.nINdzdlrmOO3ipt0XJih3snW3aSTUsA_LmFMrjZwy-I
