POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvbXBwYSIsImlkIjoiNjQ2MjY2ODk2OTNlZDE4OTNiZDAwNTIwIiwiaWF0IjoxNjg0MjU3NzUyfQ.D0TH8pIH9WaTTDYxj6AqoBxHhZWSlfBM-77FSNKBC0s

{
    "title": "Blogi Jomban",
    "author": "Joona Tölkki",
    "url": "https://www.jobe.fi",
    "likes": 9
}
